#!/usr/bin/env python3
import base64
import html
import json
import sys
import urllib.parse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_FILES = ["non-tls", "tls"]
OUT_DIR = ROOT / "dist"


def decode_source(path: Path) -> str:
    raw = path.read_text(encoding="utf-8").strip()
    return base64.b64decode(raw).decode("utf-8", "replace")


def parse_vmess_uri(line: str) -> bool:
    payload = line[len("vmess://") :]
    try:
        decoded = base64.b64decode(payload + "=" * (-len(payload) % 4)).decode("utf-8")
        data = json.loads(decoded)
    except Exception:
        return False

    required = {"add", "port", "id"}
    if not required.issubset(data):
        return False
    return True


def validate_line(line: str) -> tuple[bool, str]:
    if line.startswith(("vless://", "ss://", "trojan://")):
        parsed = urllib.parse.urlsplit(line)
        if not parsed.scheme or not parsed.netloc:
            return False, "missing scheme/netloc"
        return True, ""
    if line.startswith("vmess://"):
        return (parse_vmess_uri(line), "invalid vmess payload")
    return False, "unsupported protocol"


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    manifest = {
        "generated_at": None,
        "files": [],
        "errors": [],
    }

    total_errors = 0
    for name in SOURCE_FILES:
        source = ROOT / name
        decoded = decode_source(source)
        lines = [line for line in decoded.splitlines() if line.strip()]
        seen = set()
        file_errors = []
        valid_lines = []

        for idx, line in enumerate(lines, 1):
            ok, reason = validate_line(line)
            if not ok:
                file_errors.append({"line": idx, "value": line[:160], "reason": reason})
            if line in seen:
                file_errors.append({"line": idx, "value": line[:160], "reason": "duplicate"})
            seen.add(line)
            valid_lines.append(line)

        (OUT_DIR / f"{name}.decoded.txt").write_text("\n".join(valid_lines) + "\n", encoding="utf-8")
        (OUT_DIR / f"{name}.decoded.json").write_text(
            json.dumps({"name": name, "lines": valid_lines}, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )

        manifest["files"].append(
            {
                "name": name,
                "lines": len(lines),
                "errors": len(file_errors),
                "output_text": f"{name}.decoded.txt",
                "output_json": f"{name}.decoded.json",
            }
        )
        manifest["errors"].extend({"file": name, **err} for err in file_errors)
        total_errors += len(file_errors)

    manifest["generated_at"] = "workflow-time"
    (OUT_DIR / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    index_parts = [
        "<!doctype html>",
        "<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>",
        "<title>Decoded proxy lists</title>",
        "<style>body{font-family:system-ui,sans-serif;max-width:1100px;margin:2rem auto;padding:0 1rem}pre{white-space:pre-wrap;word-break:break-word;background:#111;color:#eee;padding:1rem;border-radius:12px;overflow:auto}code{background:#f3f3f3;padding:.15rem .35rem;border-radius:6px}section{margin:2rem 0}h1,h2{margin-bottom:.4rem}</style>",
        "</head><body>",
        "<h1>Decoded proxy lists</h1>",
        "<p>Generated by GitHub Actions. Download the raw text or inspect the JSON manifest.</p>",
        "<p><code>manifest.json</code>, <code>*.decoded.txt</code>, and <code>*.decoded.json</code> are in this publish artifact.</p>",
    ]

    if total_errors:
        index_parts.append(f"<p><strong>Validation warnings:</strong> {total_errors}</p>")

    for file_entry in manifest["files"]:
        text_name = file_entry["output_text"]
        json_name = file_entry["output_json"]
        index_parts.append(
            "<section>"
            f"<h2>{html.escape(file_entry['name'])}</h2>"
            f"<p>{file_entry['lines']} lines, {file_entry['errors']} validation issues</p>"
            f"<p><a href='{text_name}'>{text_name}</a> | <a href='{json_name}'>{json_name}</a></p>"
            f"<pre>{html.escape((OUT_DIR / text_name).read_text(encoding='utf-8'))}</pre>"
            "</section>"
        )

    index_parts.append("</body></html>")
    (OUT_DIR / "index.html").write_text("".join(index_parts), encoding="utf-8")

    if total_errors:
        print(f"validation completed with {total_errors} issue(s)", file=sys.stderr)
        return 1
    print("validation completed cleanly")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
